/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iAggregatorV3InterfaceFullSol from "./IAggregatorV3InterfaceFull.sol";
export type { iAggregatorV3InterfaceFullSol };
